### ISSUE TITLE
FabFedLib high level design - initial tasks

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#1]
The overall sentiment is to adapt (only) the Python frame code to create a fabfedlib package that can be used in companion with fablib for federation slices. The initial design tasks are:
* [x] 1. Create a trimmed `mobius-fabfed` branch that only include necessary artifacts (Python source, deployment and packaging scripts etc.)
* [x] 2. Controller design for stateful workflow, including (1) flexible integration of external resource aggregate (ERA) types, (2) handling dependency, and (3) plugins for handling stitching between ERAs with exchange of states / parameters.
* [x] 3. Framework for extensible ERA handling. Pluggable for FABRIC, SENSE, GENI, NSF clouds and beyond. The config and plugin structure should be common and flexible for identity management, authentication, resource description, provisioning and result/error report. 
* [x] 4. "Federation Slice" resource modeling that should be compatible or similar to FIM and applicable for the extensible ERAs in 3.

**Comment by disprosium8** [comment]
Updated main branch to just contain the Python framework.

**Comment by xi-yang** [comment]
@abessiar The follow up step is to use Mobius (Python) to create a working workflow. That excise should give us an idea about the basics of the current code base. 

I @xi-yang will describe a strawman FabFed workflow design in the 7/20 meeting.
