### ISSUE TITLE
FabFedLib/Mobius - User interface and workflow

### ISSUE THREAD

**Issue by disprosium8** [fabric-testbed/fabfed#2]
Driving the federation modeled workflow from the user perspective will require extensions to the existing Mobius framework. Some initial considerations that will need to be addressed:

- [x] 1. User credential handling for CF and external API access.  At the moment all resource provider credentials are explicitly setup in a config.yml file. Tooling should be extended to work with SSO (CIlogon) prompts and avoid tasks like manual project token maintenance.
- [x] 2. Extend the Mobius API to enable specification of resource details outside of config.yml.  This includes, but is not limited to, things like the slice name, resource counts, etc.
- [x] 3. ERA plugins (i.e. resource providers) will need to be invoked asynchronously with a scheme for managing dependencies between plugins. For example, we may need a successful response from a particular plugin before another dependent plugin is activated.
- [x] 4. Mobius API extensions for chaining extensible ERAs as developed in #1. (Task 3). 
- [x] 5. Support for adding services on top of provisioned resources. This includes DTNaaS demonstration and perhaps FABRIC MF services. Such persistent services will run within existing FABNetv4/v6 slices and will require reachability with node resources instantiated with FabFedLib/Mobius.

**Comment by xi-yang** [comment]
Let's use "FIM for Federated Network Topology and Stitching Workflow" Sections 1-3 for reference and add some model / schema / format related design to Section 4, as an outcome of this task.

**Comment by disprosium8** [comment]
Some initial high level slice model considerations @abessiari:

- A `Slice` interface is used internally by controller to manage user resources. User API should probably not expose this directly.
- The `Slice` manages `Node`, `Network`, and `Service` capabilities.  Services may be provider-native (as in l3vpn) or external (as in DTNaaS), so we will need a way to define how such services are invoked. 
- Some providers may only create Slices with Nodes, some with Networks and Nodes, etc. Providers do not necessarily need to implement all interfaces capabilities.
  - (Optional) Allow updated framework to continue to be useful in allocating non-federated/networked resources.
- The `Slice` interface will also require methods to retrieve state about a subset of important slice resources. For example, selected network vlans, network subnets, service endpoints, etc.

```
Slice:
  - Node nodes[]
  - Network networks[]
  - Service services[]
  
  create_slice():
     <instantiate all defined resources>
  delete_slice()
  modify_slice()
  add_resource()
  get_state(type)
...
```

- The `chi` provider in the existing code provide much of this already.  Some aspects are not implemented fully (see Network)
- Each provider client will need to ensure that CF state is managed in a way to allow fully formed slice requests to be instantiated. 
  - This means refactoring any shared state between Node/Network/Service routines.
  - Eventually modify may be introduced to make provisioning less sequential

- A `ProviderManager` orchestrates `Slice` objects.
  - Loads FABRIC Information Model objects. Used to learn constraints/dependencies on networked Slice resources.
  - Makes use of rule sets to define dependencies between resource providers
  - Defines ordering for `create` calls based on rule sets
  - Bound to user sessions to track state of `Slice` resources over time

```
ProviderManager:
  - FIM model
  - Slice slices[]
  - RuleSet rules[]
  - priority_dict -> slice ordering

  create_and_wait()
  create_async()
  get_status()
```

**Comment by abessiari** [comment]
@xi-yang @disprosium8 

I took a different approach. In this repo [fabric_model_example](https://github.com/abessiari/fabric_model_example) there is a README file and a sample config file to explain the concept/approach.  We still use yaml config for now.  This config can be converted to HCL if and when  we decide to integrate with terraform and implement a terraform plugin. 

We can discuss this later today in the meeting.

**Comment by xi-yang** [comment]
For the record, we agree to code up with the following stack and reshape the structure of this repo. 

1. A layer to model the fabfed slice in "Node / Network / Service" data structure with functions /calls to support slice lifecycle operations. 
2. A layer under 1 to support policies and rules for workflow logic with needed workflow management functions
3. A layer above 1 to to interpret user abstraction (for example a HCL compatible YAML / JSON description) that transform that into the codes / data in 1 and 2. 

The abstraction in 3 may include implicit data dependency rules that need to be translated into the internal code structure in 2. It should also be possible for explicitly defined workflow policies / rules to be added into 2 through system config or additional user input.

We should try to keep the slice data structure similar to what fablib has, to make it easy to integrate with fablib in the future.

**Comment by disprosium8** [comment]
To extend @xi-yang comments about fablib, and per Ilya's comments in our last update call, let us look at fablib's modeling of slice/node/services to make sure we 

1. don't miss anything obvious
2. evaluate it as a potential model for direct use/extension into a fabfed controller
3. ensure a consistent user experience given that our federation workflow solution will be FABRIC-focused.

https://github.com/fabric-testbed/fabrictestbed-extensions/tree/main/fabrictestbed_extensions/fablib
