### ISSUE TITLE
CloudLab provider integration 

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#22]
* [x] 1. @disprosium8 experiments with CloudLab stitching manually 
* [x] 2. @abessiari automates the provider operations based on steps learned from 1.
* [x] 3. add stitching support for the provider and prepare stitching capable service profiles

Before Production network ARM is updated, let's use FacilityPort `UKY-AL2S` as a fake for stitching tests on the DEV topology.

**Comment by disprosium8** [comment]
@abessiari and I met 2/16/2023 to discuss current workflow and succeeded in manually stitching Utah Cloudlab to FABRIC UTAH switch. 

- Use fabfed-stitch profile in fabfed Cloudlab project
- Select vlan 3211 for testing
- Utah Cloudlab VM gets 192.168.1.2 IP assignment
- FABRIC Utah switch has vlan 3211 subinterface on facility port with IP 192.168.1.10 for testing.
- ICMP/ping test works

Branch [cloudlab](https://github.com/fabric-testbed/fabfed/tree/cloudlab) has basic usage of Cloudlab portal-tools (XMLRPC) to recreate stitching workflow above. Next step is to integrate the portal-tools more closely with the fabfed provider modeling.
