### ISSUE TITLE
No summary and cleanup for aborted (partially successful) workflow

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#30]
There is no summary data can be shown for and in-progress workflow. 

Also when a workflow got stuck and aborted, there is no way to revert the provisioned portion

In one example, the FABRIC+SENSE-AWS workflow got stuck between two providers, with FABRIC slice in StackOK but VM config stuck. After aborting the workflow, there was no way to show where we were and no way to delete the provisioned portion with the FABRIC provider.

<img width="1101" alt="Screen Shot 2023-04-25 at 3 05 39 PM" src="https://user-images.githubusercontent.com/6596456/234648188-c9953918-8ec9-4414-8e49-2b4ecf3b70ff.png">

**Comment by abessiari** [comment]
@xi-yang 
Ok. That is keyboard interrupt. A workaround for now is to do apply again ... The apply was designed to "always make" progress ....

**Comment by xi-yang** [comment]
As a general solution, we need a procedure to "revert" as in some situations you would never succeed by applying again.

**Comment by abessiari** [comment]
Handling interrupts for apply and destroy. For apply we override the state.
