### ISSUE TITLE
sense-aws. fabric throws playbook exception: Couldnt create VRF

### ISSUE THREAD

**Issue by abessiari** [fabric-testbed/fabfed#41]
Exception: Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Node: fabric_node0, Site: RENC, State: Active, 
Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Node: fabric_node0, Site: RENC, State: Active, 
failed lease update- all units failed priming: Exception during create for unit: ae2604e8-3c9b-45bf-b202-a43e51f19679 (PlaybookException(Playbook has failed tasks: results: None, error_text: Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit., error: 1), [(core1.loui.net.internet2.edu, HundredGigE0/0/0/24), (agg4.ashb.net.internet2.edu, HundredGigE0/0/0/7)])#all units failed priming: Exception during create for unit: ae2604e8-3c9b-45bf-b202-a43e51f19679 (PlaybookException(Playbook has failed tasks: results: None, error_text: Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit., error: 1), [(core1.loui.net.internet2.edu, HundredGigE0/0/0/24), (agg4.ashb.net.internet2.edu, HundredGigE0/0/0/7)])#
Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Node: fabric_node0, Site: RENC, State: Active, 
Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Slice Exception: Slice Name: aes-last, Slice ID: 4291a4cf-6a74-4637-8dfb-4418758119f8: Node: fabric_node0, Site: RENC, State: Active, 
failed lease update- all units failed priming: Exception during create for unit: ae2604e8-3c9b-45bf-b202-a43e51f19679 (PlaybookException(Playbook has failed tasks: results: None, error_text: Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit., error: 1), [(core1.loui.net.internet2.edu, HundredGigE0/0/0/24), (agg4.ashb.net.internet2.edu, HundredGigE0/0/0/7)])#all units failed priming: Exception during create for unit: ae2604e8-3c9b-45bf-b202-a43e51f19679 (PlaybookException(Playbook has failed tasks: results: None, error_text: Couldnt create VRF: Couldnt create Endpoint: Couldnt find an available Unit., error: 1), [(core1.loui.net.internet2.edu, HundredGigE0/0/0/24), (agg4.ashb.net.internet2.edu, HundredGigE0/0/0/7)])#

**Comment by abessiari** [comment]
@xi-yang 
@zlion 
fabric-sense-aws, RENC, agg4.ashb.net.internet2.edu, HundredGigE0/0/0/7
I was able to provision successfully. Then I destroyed. 
But now I can no longer provision. Using same inputs, I keep getting the playbook error above from fabric.submit().

**Comment by xi-yang** [comment]
The OESS connection remained. So it had not been destroyed correctly. 

As we can see that the BGP peering with AWS was still active, the SENSE service instance must still be active. So the SENSE service wasn't canceled at that point. We will need to test more on the workflow to find out why.

<img width="1428" alt="Screen Shot 2023-06-14 at 10 49 59 PM" src="https://github.com/fabric-testbed/fabfed/assets/6596456/7b1959c2-6fb7-4d83-9c5f-d253b8de2615">

**Comment by abessiari** [comment]
@xi-yang 
@zlion 

Can we clear it so I can keep testing/developing ...?

I may have caused this issue by bypassing the destruction of sense instance to save time. 
I was focusing on fabric ....

**Comment by xi-yang** [comment]
@abessiari The SENSE service instance was deleted without being canceled. I had to manually clean it up from AWS before deleting the OESS connection. Now they are all gone.

Make sure to fix the code for the destroy logic. Never delete a SENSE service instance without seeing it in CANCEL - READY status. If seeing FAILED status, pause the workflow and ask an admin (me) to check.
