### ISSUE TITLE
Allow to destroy a workflow session when pwd is not in the workflow config folder 

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#51]
When creating a workflow session, we do `-apply` from a folder that holds the config.fab for this workflow.

Currently we have to stay in the same folder to `-destroy` this session. However, when we work with multiple workflows, it is inconsistent to always return the the original folder for the destroy op. It would work better if the session context can remember the original folder path and use that wherever we try to destroy the session.

**Comment by abessiari** [comment]
Resolved now the directory is associated with the session. The mapping is stored in a meta data file on disk.
