### ISSUE TITLE
Code structure refactoring

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/fabfed#6]
* [x] 1. Update README
* [x] 2. Replace `mobius` package with  `fabfed` package 
* [x] 3. Add `tools` and  `tests` folders as siblings to the `fabfed` folder so that the latter is dedicated to a lib package.
* [x] 4. Trim all the unused subfolders
* [x] 5. Add subfolder structure to reflect this code stack design: https://github.com/fabric-testbed/mobius-fabfed/issues/2#issuecomment-1205408139

**Comment by xi-yang** [comment]
@abessiari I suggest refactoring the `fabfed` subfolders into this structure. How do you think?

```
model: (data structures)
	- intent: user facing experiment resource description (yaml/json) and interpreter 
	- slice: internal data structure for multi-provider slice
		- resource / node / network / dependencies 

user: 
	- user identities data and authentication / authorization


controller: 
	- session: peristent context
	- policy:
	- workflow: 

provider: 
	- base
	- fabric
	- chi
	- sense
	- ...

util:

```

Then move the `config` folder to root level. Remove the `test` folder as we already had root `tests`.

**Comment by abessiari** [comment]
@xi-yang 

I have done more refactoring (interfaces for base classes) and pushed  functionality code to base classes. Slice and Provider are pretty much done. Node is almost there. I need to tackle Networks
