### ISSUE TITLE
Error setting the vlan when using cloudlab

### ISSUE THREAD

**Issue by abessiari** [fabric-testbed/fabfed#80]
2024-01-04 09:49:27,253 [controller.py:171] [ERROR] [exitval=255,code=2,output=Could not apply parameter set to script
Traceback (most recent call last):
  File "/tmp/genilib/50747.py", line 104, in <module>
    lan.setVlanTag(params.vlan)
AttributeError: 'Link' object has no attribute 'setVlanTag'
Jail py-cage-50753 execution failed with exit code 1
*** start-experiment:
    Traceback (most recent call last):
  File "/tmp/genilib/50747.py", line 104, in <module>
    lan.setVlanTag(params.vlan)
AttributeError: 'Link' object has no attribute 'setVlanTag'
Jail py-cage-50753 execution failed with exit code 1

**Comment by abessiari** [comment]
@disprosium8 
cc: @xi-yang 

There is a new issue with cloudlab. The error looks like it is on the sever side.
Please see above. Who do we need to talk to?

**Comment by xi-yang** [comment]
Leigh Stoller <lbstoller@gmail.com> is the point of contact for CloudLab. You can ask him directly or ask Ezra to relay the message.

> @disprosium8 cc: @xi-yang
> 
> There is a new issue with cloudlab. The error looks like it is on the sever side. Please see above. Who do we need to talk to?

**Comment by abessiari** [comment]
@xi-yang Yes I have slacked him and cced Ezra.

**Comment by abessiari** [comment]
Issue fixed on cloudlab side.
